# Generated by Django 5.2.8 on 2025-11-06 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone",
                    models.CharField(
                        help_text="Patient's phone number as primary identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Optional patient name", max_length=100
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("ko", "Korean"),
                            ("en", "English"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                        ],
                        default="ko",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="Date of metrics")),
                ("total_messages", models.IntegerField(default=0)),
                ("ai_handled_messages", models.IntegerField(default=0)),
                ("human_needed_messages", models.IntegerField(default=0)),
                ("completed_appointments", models.IntegerField(default=0)),
                ("average_response_time", models.DurationField(blank=True, null=True)),
                (
                    "patient_satisfaction_avg",
                    models.FloatField(
                        blank=True, help_text="Average satisfaction rating", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "System Metrics",
                "verbose_name_plural": "System Metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(help_text="Message content")),
                (
                    "direction",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("kakao", "KakaoTalk"),
                            ("wechat", "WeChat"),
                            ("line", "LINE"),
                            ("sms", "SMS"),
                            ("phone", "Phone"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "is_ai_handled",
                    models.BooleanField(
                        default=False, help_text="Whether AI processed this message"
                    ),
                ),
                (
                    "needs_human",
                    models.BooleanField(
                        default=False, help_text="Whether human intervention required"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence in handling (0-1)",
                        null=True,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("doctor", models.CharField(help_text="Doctor's name", max_length=100)),
                (
                    "procedure",
                    models.CharField(
                        help_text="Medical procedure type", max_length=200
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(help_text="Appointment date and time"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Staff Approval"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional appointment notes"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(help_text="Staff response content")),
                (
                    "response_time",
                    models.DurationField(
                        blank=True, help_text="Time to respond", null=True
                    ),
                ),
                (
                    "satisfaction_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Patient satisfaction rating 1-5",
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_responses",
                        to="core.message",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Response",
                "verbose_name_plural": "Staff Responses",
            },
        ),
    ]
