# Generated by Django 5.2.8 on 2025-11-11 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Doctor's full name", max_length=100),
                ),
                (
                    "specialization",
                    models.CharField(
                        help_text="Medical specialization", max_length=200
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone", max_length=20
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Currently active"),
                ),
                (
                    "max_daily_appointments",
                    models.IntegerField(
                        default=20, help_text="Maximum appointments per day"
                    ),
                ),
                (
                    "average_appointment_duration",
                    models.DurationField(help_text="Average appointment duration"),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.CreateModel(
            name="ProcedureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Procedure name", max_length=200)),
                (
                    "name_ko",
                    models.CharField(
                        blank=True, help_text="Korean name", max_length=200
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(
                        blank=True, help_text="Chinese name", max_length=200
                    ),
                ),
                (
                    "name_ja",
                    models.CharField(
                        blank=True, help_text="Japanese name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Procedure description"),
                ),
                (
                    "estimated_duration",
                    models.DurationField(help_text="Estimated procedure duration"),
                ),
                (
                    "requires_equipment",
                    models.TextField(
                        blank=True, help_text="Required equipment (comma-separated)"
                    ),
                ),
                (
                    "preparation_time",
                    models.DurationField(
                        blank=True,
                        help_text="Pre-procedure preparation time",
                        null=True,
                    ),
                ),
                (
                    "recovery_time",
                    models.DurationField(
                        blank=True, help_text="Post-procedure recovery time", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Type",
                "verbose_name_plural": "Procedure Types",
            },
        ),
        migrations.CreateModel(
            name="AppointmentReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheduled_send_at",
                    models.DateTimeField(help_text="When to send reminder"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When reminder was sent", null=True
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("kakao", "KakaoTalk"),
                            ("wechat", "WeChat"),
                            ("line", "LINE"),
                        ],
                        default="sms",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message_content",
                    models.TextField(help_text="Reminder message content"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error details if failed"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="core.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Reminder",
                "verbose_name_plural": "Appointment Reminders",
                "ordering": ["scheduled_send_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalTerminology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "term_en",
                    models.CharField(help_text="English medical term", max_length=200),
                ),
                (
                    "term_ko",
                    models.CharField(
                        blank=True, help_text="Korean translation", max_length=200
                    ),
                ),
                (
                    "term_zh",
                    models.CharField(
                        blank=True, help_text="Chinese translation", max_length=200
                    ),
                ),
                (
                    "term_ja",
                    models.CharField(
                        blank=True, help_text="Japanese translation", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Medical category (e.g., procedure, diagnosis)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Term description or context"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, help_text="Number of times used"),
                ),
                (
                    "accuracy_rating",
                    models.FloatField(
                        default=1.0, help_text="Translation accuracy rating (0-1)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Terminology",
                "verbose_name_plural": "Medical Terminologies",
                "indexes": [
                    models.Index(
                        fields=["term_en"], name="core_medica_term_en_873a2b_idx"
                    ),
                    models.Index(
                        fields=["category"], name="core_medica_categor_ef6171_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AppointmentWaitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_date",
                    models.DateField(help_text="Preferred appointment date"),
                ),
                (
                    "preferred_time_start",
                    models.TimeField(help_text="Preferred time range start"),
                ),
                (
                    "preferred_time_end",
                    models.TimeField(help_text="Preferred time range end"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("notified", "Notified"),
                            ("booked", "Booked"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "priority_score",
                    models.IntegerField(
                        default=0, help_text="Priority score for queue ordering"
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, help_text="When patient was notified", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When waitlist entry expires", null=True
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="core.patient",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="core.doctor",
                    ),
                ),
                (
                    "procedure_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="core.proceduretype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Waitlist",
                "verbose_name_plural": "Appointment Waitlists",
                "ordering": ["-priority_score", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchedulingOptimization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_scheduled_at",
                    models.DateTimeField(help_text="Original requested time"),
                ),
                (
                    "optimized_scheduled_at",
                    models.DateTimeField(help_text="AI-optimized time"),
                ),
                (
                    "optimization_score",
                    models.FloatField(help_text="Optimization quality score (0-1)"),
                ),
                (
                    "wait_time_reduction_minutes",
                    models.IntegerField(
                        default=0, help_text="Estimated wait time reduction"
                    ),
                ),
                (
                    "patient_accepted",
                    models.BooleanField(
                        default=False, help_text="Patient accepted optimization"
                    ),
                ),
                (
                    "optimization_reason",
                    models.TextField(blank=True, help_text="Reason for optimization"),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization",
                        to="core.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduling Optimization",
                "verbose_name_plural": "Scheduling Optimizations",
            },
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of week (0=Monday)",
                    ),
                ),
                ("start_time", models.TimeField(help_text="Availability start time")),
                ("end_time", models.TimeField(help_text="Availability end time")),
                (
                    "is_available",
                    models.BooleanField(default=True, help_text="Currently available"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="core.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Availability",
                "verbose_name_plural": "Doctor Availabilities",
                "unique_together": {("doctor", "weekday", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="TranslationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_text", models.TextField(help_text="Original text")),
                ("translated_text", models.TextField(help_text="Translated text")),
                (
                    "source_language",
                    models.CharField(help_text="Source language code", max_length=10),
                ),
                (
                    "target_language",
                    models.CharField(help_text="Target language code", max_length=10),
                ),
                (
                    "translation_service",
                    models.CharField(
                        default="google",
                        help_text="Translation service used",
                        max_length=50,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, help_text="Translation confidence (0-1)", null=True
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True, help_text="Manual quality rating (0-1)", null=True
                    ),
                ),
                (
                    "is_medical_terminology",
                    models.BooleanField(
                        default=False, help_text="Contains medical terms"
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Translation time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation History",
                "verbose_name_plural": "Translation Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_language", "target_language"],
                        name="core_transl_source__8cde9d_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_transl_created_02c2ae_idx"
                    ),
                ],
            },
        ),
    ]
