# Generated by Django 5.2.8 on 2025-12-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
